services:
    odiseo_sylius_geo_plugin.helper.ip_geo_location:
        class: Odiseo\SyliusGeoPlugin\Helper\IpGeolocationHelper
        arguments:
            - '@request_stack'
            - '@geoip2.reader'
