services:
    odiseo_sylius_geo_plugin.helper.ip_geo_localization:
        class: Odiseo\SyliusGeoPlugin\Helper\IpGeolocalizationHelper
        arguments:
            - '@request_stack'
            - '@session'
            - '@geoip2.reader'
